#!/usr/bin/env bash
## collection of commands useful for full or partial reinstall / uninstall

PODNAME=nextcloudpod

## stop and remove pod, hence also stopping and removing nested containers
podman pod stop $PODNAME && podman pod rm $PODNAME

## remove config volumes stored at ~/.local/share/containers/storage/volumes/
podman volume rm ncv_nc ncv_mariadb ncv_redis 

## remove data volume stored at /mnt/raid1/nextcloudstorage
# podman volume rm ncv_data
